<a href="https://colab.research.google.com/github/Vijaya-116/deep-learning-lab/blob/main/with_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Using keras implement the matrices multiplicaton

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

# Generate training data
def generate_data(num_samples, matrix_size):
    X = np.random.randint(0, 10, (num_samples, matrix_size, matrix_size))
    Y = np.array([np.dot(x, x) for x in X])
    return X, Y

# Define the matrix size and number of samples
matrix_size = 3
num_samples = 1000

# Generate data
X_train, Y_train = generate_data(num_samples, matrix_size)

# Reshape data for the model
X_train = X_train.reshape((num_samples, matrix_size, matrix_size, 1))
Y_train = Y_train.reshape((num_samples, matrix_size, matrix_size, 1))

# Define the model
model = Sequential([
    Flatten(input_shape=(matrix_size, matrix_size, 1)),
    Dense(matrix_size * matrix_size, activation='relu'),
    Dense(matrix_size * matrix_size, activation='linear'),
    tf.keras.layers.Reshape((matrix_size, matrix_size, 1))
])

# Compile the model
model.compile(optimizer=Adam(), loss='mean_squared_error')

# Train the model
model.fit(X_train, Y_train, epochs=10, batch_size=32)

# Evaluate the model
X_test, Y_test = generate_data(10, matrix_size)
X_test = X_test.reshape((10, matrix_size, matrix_size, 1))
Y_test = Y_test.reshape((10, matrix_size, matrix_size, 1))
loss = model.evaluate(X_test, Y_test)
print(f'Test loss: {loss}')

# Test the model with new data
X_new = np.random.randint(0, 10, (1, matrix_size, matrix_size))
X_new_reshaped = X_new.reshape((1, matrix_size, matrix_size, 1))
predictions = model.predict(X_new_reshaped)
print(f'Input matrix:\n{X_new[0]}')
print(f'Predicted product:\n{predictions[0].reshape(matrix_size, matrix_size)}')

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 5433.6050
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5169.6714
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5547.9761
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5497.5620
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5245.0391
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5110.4248
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4836.2012 
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4270.4424
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 3778.8452
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 3028.2002
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 400ms/step - loss: 2877.8523
Test loss: 2877.852294921875
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 192ms/step
Input matrix:
[[2 6 7]
 [1 6 9]
 [5 7 9]]
Predicted product:
[[39.014317  33.257652  38.38377  ]
 [21.794918  25.84046   39.384243 ]
 [ 8.4663925 19.82277   37.989212 ]]


Using Keras print prime numbers

In [2]:
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def generate_prime_data(num_samples):
    X = np.arange(num_samples)
    Y = np.array([1 if is_prime(x) else 0 for x in X])
    return X, Y

num_samples = 1000
X_train, Y_train = generate_prime_data(num_samples)
X_train = X_train.reshape(-1, 1)  # Reshape for the model input

# Define the model
model = Sequential([
    Dense(64, input_dim=1, activation='relu'),
    Dense(32, activation='relu'),
    Dense(1, activation='sigmoid')
])

# Compile the model
model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, Y_train, epochs=10, batch_size=32, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_train, Y_train)
print(f'Training accuracy: {accuracy:.4f}')

# Predict prime numbers
def predict_primes(numbers):
    predictions = model.predict(np.array(numbers).reshape(-1, 1))
    print(f'Raw predictions: {predictions.flatten()}')  # Debug: print raw predictions
    return [num for num, pred in zip(numbers, predictions) if pred > 0.5]

# Test with new numbers
test_numbers = np.arange(50, 100)
primes = predict_primes(test_numbers)
print(f'Predicted prime numbers: {primes}')

Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


25/25 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.7402 - loss: 1.4770 - val_accuracy: 0.8550 - val_loss: 0.7397
Epoch 2/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8030 - loss: 0.6481 - val_accuracy: 0.8550 - val_loss: 1.0884
Epoch 3/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8305 - loss: 0.5960 - val_accuracy: 0.8550 - val_loss: 1.0817
Epoch 4/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8442 - loss: 0.4833 - val_accuracy: 0.8550 - val_loss: 0.4954
Epoch 5/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8266 - loss: 0.4972 - val_accuracy: 0.8550 - val_loss: 0.5421
Epoch 6/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8371 - loss: 0.5271 - val_accuracy: 0.8550 - val_loss: 0.4850
Epoch 7/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8454 - loss: 0.4583 - val_accuracy: 0.8550 - val_loss: 0.4501
Epoch 8/10
25/25 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8280 - loss: 0.5304 - val_accuracy: 0.8550 - val_loss: 0.4448
Ep